/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * Bad request (e.g., missing asset parameter)
 */
export type ErrorResponseData = {
    error?: string | undefined;
};

/**
 * Bad request (e.g., missing asset parameter)
 */
export class ErrorResponse extends Error {
    error?: string | undefined;

    /** The original data that was passed to this error instance. */
    data$: ErrorResponseData;

    constructor(err: ErrorResponseData, options?: ErrorOptions) {
        super("", options);
        this.data$ = err;

        if (err.error != null) {
            this.error = err.error;
        }

        const msg = "message" in err && typeof err.message === "string" ? err.message : "";
        const content = JSON.stringify(err);
        this.message = [msg, content].filter(Boolean).join("\n");

        this.name = "ErrorResponse";
    }
}

/** @internal */
export namespace ErrorResponse$ {
    export type Inbound = {
        error?: string | undefined;
    };

    export const inboundSchema: z.ZodType<ErrorResponse, z.ZodTypeDef, Inbound> = z
        .object({
            error: z.string().optional(),
        })
        .transform((v) => {
            return new ErrorResponse({
                ...(v.error === undefined ? null : { error: v.error }),
            });
        });
    export type Outbound = {
        error?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ErrorResponse> = z
        .instanceof(ErrorResponse)
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    error: z.string().optional(),
                })
                .transform((v) => {
                    return {
                        ...(v.error === undefined ? null : { error: v.error }),
                    };
                })
        );
}
