/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class Data extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "audit" })
    audit?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "blockchains" })
    blockchains?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "chat" })
    chat?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "circulating_supply" })
    circulatingSupply?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "circulating_supply_addresses" })
    circulatingSupplyAddresses?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "contracts" })
    contracts?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "discord" })
    discord?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "kyc" })
    kyc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "liquidity" })
    liquidity?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "logo" })
    logo?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "market_cap" })
    marketCap?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "max_supply" })
    maxSupply?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    price?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "total_supply" })
    totalSupply?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "total_supply_contracts" })
    totalSupplyContracts?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "twitter" })
    twitter?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "volume" })
    volume?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "website" })
    website?: string;
}

export class Asset extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => Data)
    data?: Data;
}
