/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CryptoData extends SpeakeasyBase {
    /**
     * The blockchains on which the cryptocurrency exists
     */
    @SpeakeasyMetadata()
    @Expose({ name: "blockchains" })
    blockchains?: string[];

    /**
     * The contracts associated with the cryptocurrency
     */
    @SpeakeasyMetadata()
    @Expose({ name: "contracts" })
    contracts?: string[];

    /**
     * The unique identifier of the cryptocurrency
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * Liquidity
     */
    @SpeakeasyMetadata()
    @Expose({ name: "liquidity" })
    liquidity?: number;

    /**
     * Logo
     */
    @SpeakeasyMetadata()
    @Expose({ name: "logo" })
    logo?: string;

    /**
     * Market cap
     */
    @SpeakeasyMetadata()
    @Expose({ name: "market_cap" })
    marketCap?: number;

    /**
     * The name of the cryptocurrency
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * Price
     */
    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    price?: number;

    /**
     * Price change 1h
     */
    @SpeakeasyMetadata()
    @Expose({ name: "price_change_1h" })
    priceChange1h?: number;

    /**
     * Price change 1y
     */
    @SpeakeasyMetadata()
    @Expose({ name: "price_change_1y" })
    priceChange1y?: number;

    /**
     * Price change 24h
     */
    @SpeakeasyMetadata()
    @Expose({ name: "price_change_24h" })
    priceChange24h?: number;

    /**
     * Price change 30d
     */
    @SpeakeasyMetadata()
    @Expose({ name: "price_change_30d" })
    priceChange30d?: number;

    /**
     * Price change 7d
     */
    @SpeakeasyMetadata()
    @Expose({ name: "price_change_7d" })
    priceChange7d?: number;

    /**
     * The symbol of the cryptocurrency
     */
    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol?: string;
}
