/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class MarketHistoryResponseData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "price_history" })
    priceHistory?: Record<string, any>[];
}

export class MarketHistoryResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => MarketHistoryResponseData)
    data?: MarketHistoryResponseData;
}
