/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class Token0 extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    address?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "decimals" })
    decimals?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "logo" })
    logo?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    price?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "priceToken" })
    priceToken?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol?: string;
}

export class Token1 extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    address?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "decimals" })
    decimals?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "logo" })
    logo?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    price?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "priceToken" })
    priceToken?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol?: string;
}

export class MultiPair extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    address?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "blockchain" })
    blockchain?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "exchange" })
    exchange?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "factory" })
    factory?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "liquidity" })
    liquidity?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    price?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "protocol" })
    protocol?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "token0" })
    @Type(() => Token0)
    token0?: Token0;

    @SpeakeasyMetadata()
    @Expose({ name: "token1" })
    @Type(() => Token1)
    token1?: Token1;

    @SpeakeasyMetadata()
    @Expose({ name: "volume" })
    volume?: number;
}
