/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class SearchCryptoData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "blockchains" })
    blockchains?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "contracts" })
    contracts?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "liquidity" })
    liquidity?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "logo" })
    logo?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "market_cap" })
    marketCap?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    price?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "symbol" })
    symbol?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "twitter" })
    twitter?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "volume" })
    volume?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "website" })
    website?: string;
}
