/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class TradeHistoryResponseData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "blockchain" })
    blockchain?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date" })
    date?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "hash" })
    hash?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "token_amount" })
    tokenAmount?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "token_price" })
    tokenPrice?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value_usd" })
    valueUsd?: number;
}

export class TradeHistoryResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: TradeHistoryResponseData })
    @Expose({ name: "data" })
    @Type(() => TradeHistoryResponseData)
    data?: TradeHistoryResponseData[];
}
