/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AssetTransaction } from "./assettransaction";
import { Expose, Type } from "class-transformer";

export class Transaction extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "amount_usd" })
    amountUsd?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "asset" })
    @Type(() => AssetTransaction)
    asset?: AssetTransaction;

    @SpeakeasyMetadata()
    @Expose({ name: "blockchain" })
    blockchain?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "from" })
    from?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "hash" })
    hash?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "method_id" })
    methodId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "timestamp" })
    timestamp?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "to" })
    to?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "tx_cost" })
    txCost?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;
}
