/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type FetchAssetMetadataRequest = {
    /**
     * Name or contract address of the asset
     */
    asset: string;
    /**
     * Blockchain of the asset
     */
    blockchain?: string | undefined;
};

export type FetchAssetMetadataResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Successful response
     */
    asset?: components.Asset | undefined;
};

/** @internal */
export namespace FetchAssetMetadataRequest$ {
    export type Inbound = {
        asset: string;
        blockchain?: string | undefined;
    };

    export const inboundSchema: z.ZodType<FetchAssetMetadataRequest, z.ZodTypeDef, Inbound> = z
        .object({
            asset: z.string(),
            blockchain: z.string().optional(),
        })
        .transform((v) => {
            return {
                asset: v.asset,
                ...(v.blockchain === undefined ? null : { blockchain: v.blockchain }),
            };
        });

    export type Outbound = {
        asset: string;
        blockchain?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, FetchAssetMetadataRequest> = z
        .object({
            asset: z.string(),
            blockchain: z.string().optional(),
        })
        .transform((v) => {
            return {
                asset: v.asset,
                ...(v.blockchain === undefined ? null : { blockchain: v.blockchain }),
            };
        });
}

/** @internal */
export namespace FetchAssetMetadataResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        Asset?: components.Asset$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<FetchAssetMetadataResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            Asset: components.Asset$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.Asset === undefined ? null : { asset: v.Asset }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        Asset?: components.Asset$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, FetchAssetMetadataResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            asset: components.Asset$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.asset === undefined ? null : { Asset: v.asset }),
            };
        });
}
