/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type SearchCryptoByNameRequest = {
    /**
     * Name or symbol (or starting name/symbol) of the asset
     */
    name?: string | undefined;
};

/**
 * OK
 */
export type SearchCryptoByNameResponseBody = {
    data?: Array<components.SearchCryptoData> | undefined;
};

export type SearchCryptoByNameResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * OK
     */
    object?: SearchCryptoByNameResponseBody | undefined;
};

/** @internal */
export namespace SearchCryptoByNameRequest$ {
    export type Inbound = {
        name?: string | undefined;
    };

    export const inboundSchema: z.ZodType<SearchCryptoByNameRequest, z.ZodTypeDef, Inbound> = z
        .object({
            name: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.name === undefined ? null : { name: v.name }),
            };
        });

    export type Outbound = {
        name?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SearchCryptoByNameRequest> = z
        .object({
            name: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.name === undefined ? null : { name: v.name }),
            };
        });
}

/** @internal */
export namespace SearchCryptoByNameResponseBody$ {
    export type Inbound = {
        data?: Array<components.SearchCryptoData$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<SearchCryptoByNameResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: z.array(components.SearchCryptoData$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.data === undefined ? null : { data: v.data }),
            };
        });

    export type Outbound = {
        data?: Array<components.SearchCryptoData$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SearchCryptoByNameResponseBody> =
        z
            .object({
                data: z.array(components.SearchCryptoData$.outboundSchema).optional(),
            })
            .transform((v) => {
                return {
                    ...(v.data === undefined ? null : { data: v.data }),
                };
            });
}

/** @internal */
export namespace SearchCryptoByNameResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: SearchCryptoByNameResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<SearchCryptoByNameResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => SearchCryptoByNameResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: SearchCryptoByNameResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SearchCryptoByNameResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => SearchCryptoByNameResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
